### ISSUE TITLE
An Error I Got

### ISSUE THREAD

**Issue by spot92** [ProGamerGov/Neural-Tools#10]
UserWarning: ImportError: No module named '_tifffile'. Loading of some compressed images will be very slow. Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "ImportError: No module named '_tifffile'. "
Traceback (most recent call last):
  File "linear_color_transfer.py", line 4, in <module>
    from skimage import io,transform,img_as_float
  File "C:\Users\lukec\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\__init__.py", line 2, in <module>
    from .hough_transform import (hough_line, hough_line_peaks,
  File "C:\Users\lukec\AppData\Local\Programs\Python\Python36\lib\site-packages\skimage\transform\hough_transform.py", line 2, in <module>
    from ._hough_transform import (_hough_circle,
  File "__init__.pxd", line 918, in init skimage.transform._hough_transform
ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

I installed the packages, any idea what is going on here?

**Comment by ProGamerGov** [comment]
How did you install the required packages?

If you installed them with pip, then try running: 

```
pip3 install --upgrade scikit-image imageio numpy scipy
```

That should replace any old versions of those packages that you may have downloaded. 

If that doesn't work, then try this:

```
pip3 uninstall scikit-image imageio numpy scipy
pip3 install --upgrade scikit-image imageio numpy scipy
```

That should fix any links between the packages.

**Comment by spot92** [comment]
Thanks! For some reason when I was trying to upgrade/install separately, it was telling me I was up to date. I'm probably just an idiot. You are the real MVP.
