### ISSUE TITLE
Comment on installation of python packages 

### ISSUE THREAD

**Issue by htoyryla** [ProGamerGov/Neural-Tools#3]
In README.md, you write "If you already have Neural-Style up and running, then you should only need to install python-skimage."

However, because neural-style uses lua and torch, having it installed guarantees nothing concerning scipy and numpy, which are python packages, so I don't really get what the sentence quoted above tries to say.

**Comment by ProGamerGov** [comment]
@htoyryla Thank for your bringing this mistake to my attention. 

I think I was testing the code on my Neural-Style AMI at the time I was making the ReadMe, and I assumed what I had previously installed was only from the Neural-Style installation process.
