### ISSUE TITLE
Default (pca) color mode occasionally creates rectangular artifacts

### ISSUE THREAD

**Issue by rahidz** [ProGamerGov/Neural-Tools#6]
Seems to happen very rarely and seemingly at random...

chol and sym options both work as expected (and this may be a newbie question, but what do these three options represent/mean?)

Example:

Source image: ![vt](https://user-images.githubusercontent.com/22056619/45052867-55ebe880-b056-11e8-8162-354a5b810b46.jpg)

Target image: ![sk2](https://user-images.githubusercontent.com/22056619/45052827-39e84700-b056-11e8-9e92-4d44517b010d.jpg)

Result: ![sk1vt](https://user-images.githubusercontent.com/22056619/45052732-d9f1a080-b055-11e8-9ae1-228c37e6f74a.png)

**Comment by ProGamerGov** [comment]
@rahidz 

Have you had this occur with any other source and target images? Have you had this happen with any of the other color transfer modes? 

I've seen something similar looking happen with JPEG artifacts, but nothing like your example here. Maybe it's the source image having just two colors, and the transfer algorithm not liking that?
